name = "allpaystore-worker"
main = "allpaystore-worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

[route]
pattern = "allpaystore.com/*"
zone_name = "allpaystore.com"

[[routes]]
pattern = "www.allpaystore.com/*"
zone_name = "allpaystore.com"
