name = "allpaystore-worker"
main = "allpaystore_worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[routes]]
pattern = "allpaystore.com/*"
zone_name = "allpaystore.com"

[[d1_databases]]
binding = "DB"
database_name = "allcare_stats"
database_id = "d53a86d3-c541-4a3d-9358-bca98b1f71b4"
